### ISSUE TITLE
Throwing a full stack of cods in the water only produces 1 cod.

### ISSUE THREAD

**Issue by medsal15** [TheIllusiveC4/CombustiveFishing#1]
Was expecting to get my 16 cods back

**Comment by TheIllusiveC4** [comment]
My apologies, like a fool I had forgotten to check for the stack count. I just pushed out a new update, 1.0.2, that fixes this problem. Thank you for submitting this issue.

**Comment by ghost** [comment]
@medsal15 A stack is only 16?
