### ISSUE TITLE
Cant Make The Rod

### ISSUE THREAD

**Issue by AHSUnityDev** [TheIllusiveC4/CombustiveFishing#6]
#### Versions 1.12.2 Combustive Fishing:
* Forge: 1.12.2-14.2.3.5.2825
#### Steps to Reproduce:
1. Combining all the materials  in the crafting table gives me nothing

**Comment by TheIllusiveC4** [comment]
You're on 1.12.2, so you need to make the Golden Rod instead. It's down in the description on the Curse page, under "1.12.x Overview".
