### ISSUE TITLE
searing sword rebalacing

### ISSUE THREAD

**Issue by EternalOne11** [TheIllusiveC4/CombustiveFishing#9]
I was wondering if you could rebalance the searing sword since it has a higher attack speed than most weapons in the vanilla game and does a higher base dmg. I was wondering if you could rebalance it to match vanilla more. If not that is fine but I would rather know why.

**Comment by TheIllusiveC4** [comment]
I don't think that's an issue. It has relatively low durability, requires you to fish in the Nether to get its ingredients, and cannot be enchanted. Despite its higher stats, it's strictly worse than having a Diamond sword and it comes later in progression. Its only major use, and what it was intended for, is as an impromptu sword that you can craft in the Nether without going to the Overworld for materials.

**Comment by Hanyuu123** [comment]
I think it is a bug but I can enchant it which makes it super busted.

> I don't think that's an issue. It has relatively low durability, requires you to fish in the Nether to get its ingredients, and cannot be enchanted. Despite its higher stats, it's strictly worse than having a Diamond sword and it comes later in progression. Its only major use, and what it was intended for, is as an impromptu sword that you can craft in the Nether without going to the Overworld for materials.
